language: node_js
node_js:
  - 4
  - 6
  - node
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  on:
    branch: gh-pages
